import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:go_router/go_router.dart';
import '../../data/models/community_question_model.dart';
import '../../data/models/traffic_report_model.dart';
import '../providers/community_providers.dart';
import 'package:flowroute/features/auth/presentation/providers/auth_providers.dart';
import 'package:flowroute/features/profile/presentation/providers/profile_providers.dart';

class AskQuestionScreen extends ConsumerStatefulWidget {
  const AskQuestionScreen({super.key});

  @override
  ConsumerState<AskQuestionScreen> createState() => _AskQuestionScreenState();
}

class _AskQuestionScreenState extends ConsumerState<AskQuestionScreen> {
  final _textController = TextEditingController();
  bool _isLoading = false;
  bool _isReport = false; // false = question, true = report
  String _selectedReportType = 'Heavy Traffic';
  String _selectedSeverity = 'Medium';

  final List<String> _reportTypes = [
    'Heavy Traffic',
    'Accident',
    'Road Block',
    'Construction',
    'Road Closure',
    'Flooding',
    'Pothole',
    'Broken Traffic Light',
    'Police Activity',
    'Vehicle Breakdown',
    'Debris on Road',
    'Poor Road Conditions',
  ];

  final List<String> _severities = ['Heavy', 'Medium', 'Light'];

  @override
  void dispose() {
    _textController.dispose();
    super.dispose();
  }

  Future<void> _handleSubmit() async {
    final text = _textController.text.trim();
    if (text.isEmpty) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Please enter some text')));
      return;
    }

    setState(() => _isLoading = true);

    try {
      final user = ref.watch(currentUserProvider);
      final profile = await ref.read(profileProvider.future);

      print('🔵 User: ${user?.id}');
      print('🔵 Profile username: ${profile?.username}');

      final userName = profile?.username ?? 'Guest';
      final userId = user?.id;

      print('🔵 Final userName: $userName');

      if (_isReport) {
        // Post traffic report
        final report = TrafficReportModel(
          id: '', // Will be generated by Supabase
          reporterId: userId,
          reporterName: userName,
          reportType: _selectedReportType,
          description: text,
          location: null, // TODO: Add location picker
          imageUrl: null, // TODO: Add image upload
          severity: _selectedSeverity,
          createdAt: DateTime.now(),
        );
        await ref.read(communityRepositoryProvider).postReport(report);
      } else {
        // Post question
        final question = CommunityQuestionModel(
          id: '', // Will be generated by Supabase
          askerId: userId,
          askerName: userName,
          questionText: text,
          location: null, // TODO: Add location picker
          imageUrl: null, // TODO: Add image upload
          createdAt: DateTime.now(),
        );
        await ref.read(communityRepositoryProvider).postQuestion(question);
      }

      // Refresh the community posts
      ref.invalidate(communityQuestionsProvider);
      ref.invalidate(trafficReportsProvider);

      if (mounted) {
        context.pop();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(_isReport ? 'Report posted!' : 'Question posted!'),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF121212),
      appBar: AppBar(
        backgroundColor: const Color(0xFF121212),
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.close_rounded, color: Colors.white),
          onPressed: () => context.pop(),
        ),
        centerTitle: true,
        title: Text(
          'Ask Question or Report',
          style: GoogleFonts.outfit(
            color: Colors.white,
            fontWeight: FontWeight.bold,
            fontSize: 18,
          ),
        ),
      ),
      body: LayoutBuilder(
        builder: (context, constraints) {
          return SingleChildScrollView(
            child: ConstrainedBox(
              constraints: BoxConstraints(minHeight: constraints.maxHeight),
              child: Padding(
                padding: const EdgeInsets.all(24.0),
                child: IntrinsicHeight(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      // Toggle between Question and Report
                      Row(
                        children: [
                          Expanded(
                            child: _buildToggleButton(
                              'Question',
                              !_isReport,
                              () {
                                setState(() => _isReport = false);
                              },
                            ),
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: _buildToggleButton('Report', _isReport, () {
                              setState(() => _isReport = true);
                            }),
                          ),
                        ],
                      ),
                      const SizedBox(height: 24),

                      // Report Type Selector (only for reports)
                      if (_isReport) ...[
                        Text(
                          'Report Type',
                          style: GoogleFonts.outfit(
                            color: Colors.white,
                            fontWeight: FontWeight.bold,
                            fontSize: 14,
                          ),
                        ),
                        const SizedBox(height: 8),
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 16),
                          decoration: BoxDecoration(
                            color: const Color(0xFF1E1E24),
                            borderRadius: BorderRadius.circular(12),
                          ),
                          child: DropdownButton<String>(
                            value: _selectedReportType,
                            isExpanded: true,
                            dropdownColor: const Color(0xFF1E1E24),
                            style: GoogleFonts.outfit(color: Colors.white),
                            underline: const SizedBox(),
                            items: _reportTypes.map((type) {
                              return DropdownMenuItem(
                                value: type,
                                child: Text(type),
                              );
                            }).toList(),
                            onChanged: (value) {
                              setState(() => _selectedReportType = value!);
                            },
                          ),
                        ),
                        const SizedBox(height: 16),
                      ],

                      // Severity Selector (only for reports)
                      if (_isReport) ...[
                        Text(
                          'Severity',
                          style: GoogleFonts.outfit(
                            color: Colors.white,
                            fontWeight: FontWeight.bold,
                            fontSize: 14,
                          ),
                        ),
                        const SizedBox(height: 8),
                        Row(
                          children: _severities.map((severity) {
                            final isSelected = _selectedSeverity == severity;
                            return Expanded(
                              child: Padding(
                                padding: const EdgeInsets.only(right: 8),
                                child: GestureDetector(
                                  onTap: () => setState(
                                    () => _selectedSeverity = severity,
                                  ),
                                  child: Container(
                                    padding: const EdgeInsets.symmetric(
                                      vertical: 12,
                                    ),
                                    decoration: BoxDecoration(
                                      color: isSelected
                                          ? const Color(0xFF2962FF)
                                          : const Color(0xFF1E1E24),
                                      borderRadius: BorderRadius.circular(12),
                                    ),
                                    child: Text(
                                      severity,
                                      textAlign: TextAlign.center,
                                      style: GoogleFonts.outfit(
                                        color: Colors.white,
                                        fontWeight: isSelected
                                            ? FontWeight.bold
                                            : FontWeight.normal,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            );
                          }).toList(),
                        ),
                        const SizedBox(height: 24),
                      ],

                      Text(
                        _isReport ? 'Description' : 'Your question',
                        style: GoogleFonts.outfit(
                          color: Colors.white,
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                      const SizedBox(height: 12),
                      Container(
                        height: 200,
                        padding: const EdgeInsets.all(16),
                        decoration: BoxDecoration(
                          color: const Color(0xFF1E1E24),
                          borderRadius: BorderRadius.circular(16),
                        ),
                        child: TextField(
                          controller: _textController,
                          maxLines: null,
                          style: GoogleFonts.outfit(color: Colors.white),
                          decoration: InputDecoration(
                            hintText: _isReport
                                ? 'Describe the traffic issue...'
                                : 'e.g., Is the bridge open?',
                            hintStyle: GoogleFonts.outfit(
                              color: Colors.white38,
                            ),
                            border: InputBorder.none,
                          ),
                        ),
                      ),
                      const SizedBox(height: 24),
                      Row(
                        children: [
                          _buildActionButton(
                            Icons.location_on_outlined,
                            'Add\nLocation',
                          ),
                          const SizedBox(width: 16),
                          _buildActionButton(
                            Icons.camera_alt_outlined,
                            'Add Photo',
                          ),
                        ],
                      ),
                      const Spacer(),
                      ElevatedButton(
                        onPressed: () {
                          context.push('/ai-chat');
                        },
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF2962FF),
                          padding: const EdgeInsets.symmetric(vertical: 16),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(30),
                          ),
                          elevation: 0,
                        ),
                        child: Text(
                          'Ask FlowRoute AI',
                          style: GoogleFonts.outfit(
                            color: Colors.white,
                            fontWeight: FontWeight.bold,
                            fontSize: 16,
                          ),
                        ),
                      ),
                      const SizedBox(height: 16),
                      _isLoading
                          ? const Center(
                              child: CircularProgressIndicator(
                                color: Colors.blueAccent,
                              ),
                            )
                          : OutlinedButton(
                              onPressed: _handleSubmit,
                              style: OutlinedButton.styleFrom(
                                backgroundColor: const Color(0xFF1E1E24),
                                side: BorderSide.none,
                                padding: const EdgeInsets.symmetric(
                                  vertical: 16,
                                ),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(30),
                                ),
                              ),
                              child: Text(
                                'Add to Community',
                                style: GoogleFonts.outfit(
                                  color: Colors.white,
                                  fontWeight: FontWeight.bold,
                                  fontSize: 16,
                                ),
                              ),
                            ),
                      const SizedBox(height: 16),
                    ],
                  ),
                ),
              ),
            ),
          );
        },
      ),
    );
  }

  Widget _buildToggleButton(String label, bool isSelected, VoidCallback onTap) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 12),
        decoration: BoxDecoration(
          color: isSelected ? const Color(0xFF2962FF) : const Color(0xFF1E1E24),
          borderRadius: BorderRadius.circular(12),
        ),
        child: Text(
          label,
          textAlign: TextAlign.center,
          style: GoogleFonts.outfit(
            color: Colors.white,
            fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
          ),
        ),
      ),
    );
  }

  Widget _buildActionButton(IconData icon, String label) {
    return Column(
      children: [
        Container(
          width: 56,
          height: 56,
          decoration: BoxDecoration(
            color: const Color(0xFF1E1E24),
            shape: BoxShape.circle,
            border: Border.all(color: Colors.white10),
          ),
          child: Icon(icon, color: Colors.white, size: 24),
        ),
        const SizedBox(height: 8),
        Text(
          label,
          textAlign: TextAlign.center,
          style: GoogleFonts.outfit(
            color: Colors.white,
            fontSize: 12,
            fontWeight: FontWeight.w500,
          ),
        ),
      ],
    );
  }
}
